Sessions redux
cockroachdb/ui pull request #187
Opened 2021-01-28 14:45 UTC by elkmaster

all functions except alerts about success\error on query termination. tbd

2021-01-29 11:23 UTC, koorosh requested changes
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: all files reviewed, 11 unresolved discussions (waiting on @dhartunian, @elkmaster, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/api/terminateQueryApi.ts, line 4 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCK5gbDNe9De-6vmcN:-MSCK5gc5RvqYz41M21h:b-hkbsqu) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/api/terminateQueryApi.ts#L4)):*
> ```XML
> import { fetchData } from "src/api";
> 
> const STATUS_PREFIX = "_status";
> ```

it has to start with leading slash: `/_status`
___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 46 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCLRTfBvyRwm1vRugx:-MSCLRTfBvyRwm1vRugy:b4674fw) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L46)):*
> ```XML
> //import {refreshSessions} from "src/redux/apiReducers";
> 
> type ICancelQueryRequest = any;
> ```

Can we define concrete type here?
___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 53 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCK_AlAedVPpompYbW:-MSCK_AlAedVPpompYbX:bjvnh3l) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L53)):*
> ```XML
>   sessionError: Error | null;
>   //refreshSessions: typeof refreshSessions;
>   refreshSessions: any;
> ```

@elkmaster , can we provide concrete type for `refreshSessions`? 
It probably expects something like this:
```
refreshSessions: () => void;
```
___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 83 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCRZWj1avK25xHV37f:-MSCRZWj1avK25xHV37g:bvjh8ol) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L83)):*
> ```XML
> 
>   componentDidMount() {
>     this.props.refreshSessions();
> ```

This page depends on `nodeNames` but it never requests (or refreshes) nodes.
It is necessary to request nodes when session details page is open directly and any other pages were opened before.
```
this.props.refreshNodes();
this.props.refreshNodesLiveness();
```
___
*[packages/cluster-ui/src/sessions/sessionDetailsPage.fixture.ts, line 44 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCT7O378Mw8CTeByat:-MSCT7O378Mw8CTeByau:b-87f2c7) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetailsPage.fixture.ts#L44)):*
> ```XML
>   },
>   //refreshSessions: (() => {}) as (typeof refreshSessions),
>   refreshSessions: (() => {}) as any,
> ```

Can we provide concrete types here?
___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 48 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCYvkyAdfPBA8gtG5e:-MSCYvkyAdfPBA8gtG5f:b-hzv2gt) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPage.tsx#L48)):*
> ```XML
> const sortableTableCx = classNames.bind(sortableTableStyles);
> 
> type ICancelQueryRequest = any;
> ```

Can we use concrete types here?
___
*[packages/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 154 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCYznWAOxRayU-ZtFN:-MSCYznWAOxRayU-ZtFO:b-hzv2gt) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPage.fixture.ts#L154)):*
> ```XML
>   sessionsError: null,
>   refreshSessions: (() => {}) as any,
>   cancelSession: (() => {}) as any,
> ```

Can we use concrete types here?
___
*[packages/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 174 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCZ4NPDzh7MjbgWNm5:-MSCZ4NPDzh7MjbgWNm6:b-hzv2gt) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPage.fixture.ts#L174)):*
> ```XML
>   sessions: [],
>   sessionsError: null,
>   refreshSessions: (() => {}) as any,
> ```

Can we use concrete types here?
___
*[packages/cluster-ui/src/sessions/sessionsPageConnected.tsx, line 25 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCZHj06_pqXaVUPS5d:-MSCZHj06_pqXaVUPS5e:btwt04h) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPageConnected.tsx#L25)):*
> ```XML
> export const selectSessions = createSelector(
>   (state: AppState) => state.adminUI.sessions,
>   (_state: AppState, props: RouteComponentProps) => props,
> ```

Do we need this selector? It looks like `props` is not used anywhere.
___
*[packages/cluster-ui/src/sessions/sessionsPageConnected.tsx, line 39 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCZZFf9FLoVMN43mgt:-MSCZZFg7UVxspeCRE4h:b-arjv82) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPageConnected.tsx#L39)):*
> ```XML
> );
> 
> // tslint:disable-next-line:variable-name
> ```

We don't use `tslint` so this directive can be removed
___
*[packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts, line 17 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCg8rA6UZhlgNllYDb:-MSCg8rA6UZhlgNllYDc:b-vvebmt) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts#L17)):*
> ```XML
> import { terminateQuery, terminateSession } from "src/api/terminateQueryApi";
> import { actions as SessionsActions } from "src/store/sessions";
> import { actions } from "./terminateQuery.reducer"
> ```

Would be good to follow some convention for importing actions, to distinguish one from another.


<!-- Sent from Reviewable.io -->

2021-02-01 13:04 UTC, elkmaster reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: 6 of 21 files reviewed, 11 unresolved discussions (waiting on @dhartunian, @koorosh, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/api/terminateQueryApi.ts, line 4 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCK5gbDNe9De-6vmcN:-MSSflll2bQA82w9Tne-:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/api/terminateQueryApi.ts#L4)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

it has to start with leading slash: `/_status`
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 46 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCLRTfBvyRwm1vRugx:-MSSfmKs-5huYrNPNhOt:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L46)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can we define concrete type here?
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 53 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCK_AlAedVPpompYbW:-MSSfmnK1VAGoJ0z4faL:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L53)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

@elkmaster , can we provide concrete type for `refreshSessions`? 
It probably expects something like this:
```
refreshSessions: () => void;
```
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 83 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCRZWj1avK25xHV37f:-MSSfnB78oovp92nDOeV:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L83)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

This page depends on `nodeNames` but it never requests (or refreshes) nodes.
It is necessary to request nodes when session details page is open directly and any other pages were opened before.
```
this.props.refreshNodes();
this.props.refreshNodesLiveness();
```
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionDetailsPage.fixture.ts, line 44 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCT7O378Mw8CTeByat:-MSSfoAh5qtyTahDv5B-:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetailsPage.fixture.ts#L44)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can we provide concrete types here?
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 48 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCYvkyAdfPBA8gtG5e:-MSSfooC7VQn1JqxoiDf:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPage.tsx#L48)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can we use concrete types here?
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 154 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCYznWAOxRayU-ZtFN:-MSSfpaa0NOttZWioBxP:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPage.fixture.ts#L154)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can we use concrete types here?
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 174 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCZ4NPDzh7MjbgWNm5:-MSSfpwB2dVDMR0LxlfK:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPage.fixture.ts#L174)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can we use concrete types here?
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionsPageConnected.tsx, line 25 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCZHj06_pqXaVUPS5d:-MSSfqMqC0lCGZ-zcyBo:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPageConnected.tsx#L25)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Do we need this selector? It looks like `props` is not used anywhere.
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/sessions/sessionsPageConnected.tsx, line 39 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCZZFf9FLoVMN43mgt:-MSSfqos25HEg2gztCAd:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPageConnected.tsx#L39)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

We don't use `tslint` so this directive can be removed
</blockquote></details>

Done.
___
*[packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts, line 17 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCg8rA6UZhlgNllYDb:-MSSfrec5C2uEw55oIOT:b-896fix) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts#L17)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Would be good to follow some convention for importing actions, to distinguish one from another.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-01 20:48 UTC, dhartunian requested changes
> Reviewed 6 of 20 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: all files reviewed, 13 unresolved discussions (waiting on @elkmaster, @koorosh, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/store/terminateQuery/terminateQuery.reducer.ts, line 8 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSUIMsg5RVlcelX0jgF:-MSUIMsg5RVlcelX0jgG:b-ffl7zo) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/store/terminateQuery/terminateQuery.reducer.ts#L8)):*
> ```XML
> type CancelQueryResponse = cockroach.server.serverpb.CancelQueryResponse;
> 
> export type TerninateQueryState = {
> ```

replace `Terninate` with `Terminate` across the file.
___
*[packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts, line 34 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSUIw8bC2j2ni8CLdqB:-MSUIw8bC2j2ni8CLdqC:bgdhf8n) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts#L34)):*
> ```XML
>     yield put(sessionsActions.invalidated());
>     yield put(sessionsActions.refresh());
>     //yield put(terminateSessionAlertLocalSetting.set({ show: true, status: "SUCCESS"}));
> ```

Why does the existing implementation need this alert?
Can you put a // TODO comment here (or elsewhere) detailing what's missing here so we know what to add later. I assume this is used to power the popup alert in the corner.


<!-- Sent from Reviewable.io -->

2021-02-02 07:57 UTC, koorosh requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: all files reviewed, 12 unresolved discussions (waiting on @elkmaster, @koorosh, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 46 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCLRTfBvyRwm1vRugx:-MSWWjO_4FGCndgZsbsX:bz5x5i4) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L46)):*
<details><summary><i>Previously, elkmaster wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`ICancelQueryRequest` type is not used anymore. 
___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 53 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCK_AlAedVPpompYbW:-MSWdthJBd1Dt3eL2vlC:b-p6unm0) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L53)):*
<details><summary><i>Previously, elkmaster wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`typeof sessionsActions.refresh` doesn't provide the same type as expected for `refreshSessions` callback.

`typeof sessionsActions.refresh` is equal to something like this: `() => ActionCreator<T>` but `refreshSessions` expects `() => void` type.
___
*[packages/cluster-ui/src/sessions/sessionsDetailsConnected.stories.tsx, line 22 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSWXXO18pyJaFzyA9cb:-MSWXXO18pyJaFzyA9cc:b-ynebwp) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/sessions/sessionsDetailsConnected.stories.tsx#L22)):*
> ```XML
> import { Route } from "react-router-dom";
> 
> const TEST_ID = "165f9819-2feb-40f0-0000-000000000001";
> ```

Can `sessionId` be retrieved dynamically?
___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 51 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSWYhWE6IiFYv5W2k2_:-MSWYhWE6IiFYv5W2k2a:b-9766lg) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/sessions/sessionsPage.tsx#L51)):*
> ```XML
> interface OwnProps {
>   sessions: SessionInfo[];
>   sessionsError: Error | Error[];
> ```

When it can receive an array of errors? 
___
*[packages/cluster-ui/src/sessions/sessionsPageConnected.tsx, line 25 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCZHj06_pqXaVUPS5d:-MSWhSsC3NIqe3oCmZ27:b-g6h6pj) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPageConnected.tsx#L25)):*
<details><summary><i>Previously, elkmaster wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I suggested to remove second selector completely (`(_state: AppState, props: RouteComponentProps) => props,`) because it's not used then in aggregation function.
___
*[packages/cluster-ui/src/util/proto.ts, line 25 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSWilfpBvx9WYDxNcUF:-MSWilfpBvx9WYDxNcUG:b-njh0ev) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/util/proto.ts#L25)):*
> ```XML
> 
> export function accumulateMetrics(nodeStatuses: INodeStatus[]): INodeStatus[] {
>   return Array.isArray(nodeStatuses)
> ```

It's quite confusing validation because function argument type is expecting an array type only.
Would it be more convenient to check for null/undefined value or provide default value for argument to avoid any conditions inside of function?

```
function accumulateMetrics(nodeStatuses: INodeStatus[] = []) { ... }
```


<!-- Sent from Reviewable.io -->

2021-02-02 14:28 UTC, elkmaster reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: 12 of 21 files reviewed, 12 unresolved discussions (waiting on @dhartunian, @koorosh, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 46 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCLRTfBvyRwm1vRugx:-MSY6NilBA7QZPZuwQ5s:bb7f2mf) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L46)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

`ICancelQueryRequest` type is not used anymore. 
</blockquote></details>

done
___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 53 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCK_AlAedVPpompYbW:-MSY6QSS0onQOqo4CBDD:bb7f2mf) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L53)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

`typeof sessionsActions.refresh` doesn't provide the same type as expected for `refreshSessions` callback.

`typeof sessionsActions.refresh` is equal to something like this: `() => ActionCreator<T>` but `refreshSessions` expects `() => void` type.
</blockquote></details>

done
___
*[packages/cluster-ui/src/sessions/sessionsDetailsConnected.stories.tsx, line 22 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSWXXO18pyJaFzyA9cb:-MSY6Tdb4xqqEfUlTq-L:bljfok0) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/sessions/sessionsDetailsConnected.stories.tsx#L22)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can `sessionId` be retrieved dynamically?
</blockquote></details>

no easy way to do it. we need to know id before the page renders. but we fetch sessions on didMount.
___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 51 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSWYhWE6IiFYv5W2k2_:-MSY6hZn2yV0CUoI22Cd:btm92us) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/sessions/sessionsPage.tsx#L51)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

When it can receive an array of errors? 
</blockquote></details>

Good question, I do not know specific example. But looking in protobuf we have an array type:

![Screenshot 2021-02-02 at 16.12.39.png](https://files.reviewableusercontent.io/images/reviewable/12850886/N-adjWyXsuY3I7d6_9x04C_C/Screenshot%202021-02-02%20at%2016.12.39.png)
 
so seems like it  is possible?
___
*[packages/cluster-ui/src/sessions/sessionsPageConnected.tsx, line 25 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCZHj06_pqXaVUPS5d:-MSY7D6CER-usUyfJYIr:bb7f2mf) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPageConnected.tsx#L25)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I suggested to remove second selector completely (`(_state: AppState, props: RouteComponentProps) => props,`) because it's not used then in aggregation function.
</blockquote></details>

done
___
*[packages/cluster-ui/src/store/terminateQuery/terminateQuery.reducer.ts, line 8 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSUIMsg5RVlcelX0jgF:-MSY7EsP0anhFYAtFU5Z:bb7f2mf) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/store/terminateQuery/terminateQuery.reducer.ts#L8)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

replace `Terninate` with `Terminate` across the file.
</blockquote></details>

done
___
*[packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts, line 34 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSUIw8bC2j2ni8CLdqB:-MSY7Gte6fLAx8-w6ejk:bfebcp0) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts#L34)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Why does the existing implementation need this alert?
Can you put a // TODO comment here (or elsewhere) detailing what's missing here so we know what to add later. I assume this is used to power the popup alert in the corner.
</blockquote></details>

Added todo comment in top of the file
___
*[packages/cluster-ui/src/util/proto.ts, line 25 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSWilfpBvx9WYDxNcUF:-MSY7Vg87lEI_E3iOLn3:bs3w6m7) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/util/proto.ts#L25)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It's quite confusing validation because function argument type is expecting an array type only.
Would it be more convenient to check for null/undefined value or provide default value for argument to avoid any conditions inside of function?

```
function accumulateMetrics(nodeStatuses: INodeStatus[] = []) { ... }
```
</blockquote></details>

To avoid an error and extra checks I've just updated selector that was causing the issue:
`export const nodeStatusesSelector = (state: AppState) =>
  state.adminUI.nodes.data || [] ;`


<!-- Sent from Reviewable.io -->

2021-02-03 14:42 UTC, koorosh requested changes
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: all files reviewed, 8 unresolved discussions (waiting on @dhartunian, @elkmaster, @koorosh, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 53 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCK_AlAedVPpompYbW:-MSc7lzlEDjb8T3sW5ce:b-ocfnpa) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L53)):*
<details><summary><i>Previously, elkmaster wrote…</i></summary><blockquote>

done
</blockquote></details>

```
  cancelSession: () => void;
  cancelQuery: () => void;
```
these functions should expect following argument types respectively: `cockroach.server.serverpb.CancelSessionRequest` and `cockroach.server.serverpb.CancelQueryRequest`
___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 51 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSWYhWE6IiFYv5W2k2_:-MSc90dPD8DRAJ2gRQtl:b3ljj9q) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/sessions/sessionsPage.tsx#L51)):*
<details><summary><i>Previously, elkmaster wrote…</i></summary><blockquote>

Good question, I do not know specific example. But looking in protobuf we have an array type:

![Screenshot 2021-02-02 at 16.12.39.png](https://files.reviewableusercontent.io/images/reviewable/12850886/N-adjWyXsuY3I7d6_9x04C_C/Screenshot%202021-02-02%20at%2016.12.39.png)
 
so seems like it  is possible?
</blockquote></details>

Got it, you're right! 
___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 51 at r3](https://reviewable.io/reviews/cockroachdb/ui/187#-MSc9HyZB5X_JBzNVH5m:-MSc9HyZB5X_JBzNVH5n:b-lta06n) ([raw file](https://github.com/cockroachdb/ui/blob/5dda8a4c8e93014cf67e01548245caeab64671e6/packages/cluster-ui/src/sessions/sessionsPage.tsx#L51)):*
> ```XML
>   refreshSessions: () => void;
>   cancelSession: () => void;
>   cancelQuery: () => void;
> ```

see comment above, cancelSession and cancelQuery functions expect arguments
___
*[packages/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 154 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCYznWAOxRayU-ZtFN:-MScK3nD72AJNsFj-me0:b-rxk9bx) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPage.fixture.ts#L154)):*
<details><summary><i>Previously, elkmaster wrote…</i></summary><blockquote>

Done.
</blockquote></details>

see comment above for cancelSession and cancelQuery funcs
___
*[packages/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 175 at r3](https://reviewable.io/reviews/cockroachdb/ui/187#-MScKDp991mpZC7917mC:-MScKDp991mpZC7917mD:b-rxk9bx) ([raw file](https://github.com/cockroachdb/ui/blob/5dda8a4c8e93014cf67e01548245caeab64671e6/packages/cluster-ui/src/sessions/sessionsPage.fixture.ts#L175)):*
> ```XML
>   refreshSessions: () => {},
>   cancelSession: () => {},
>   cancelQuery: () => {},
> ```

see comment above for cancelSession and cancelQuery funcs


<!-- Sent from Reviewable.io -->

2021-02-09 14:01 UTC, elkmaster reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: 13 of 22 files reviewed, 8 unresolved discussions (waiting on @dhartunian, @koorosh, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/sessions/sessionDetails.tsx, line 53 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCK_AlAedVPpompYbW:-MT64yU-2EfK3CV2Bksf:b-7ql1td) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionDetails.tsx#L53)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

```
  cancelSession: () => void;
  cancelQuery: () => void;
```
these functions should expect following argument types respectively: `cockroach.server.serverpb.CancelSessionRequest` and `cockroach.server.serverpb.CancelQueryRequest`
</blockquote></details>

fixed
___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 51 at r3](https://reviewable.io/reviews/cockroachdb/ui/187#-MSc9HyZB5X_JBzNVH5m:-MT651KQC9j5R80ZZAIN:b-qssecl) ([raw file](https://github.com/cockroachdb/ui/blob/5dda8a4c8e93014cf67e01548245caeab64671e6/packages/cluster-ui/src/sessions/sessionsPage.tsx#L51)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

see comment above, cancelSession and cancelQuery functions expect arguments
</blockquote></details>

fixed
___
*[packages/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 154 at r1](https://reviewable.io/reviews/cockroachdb/ui/187#-MSCYznWAOxRayU-ZtFN:-MT654J7-qNPti4cD9WR:b-qssecl) ([raw file](https://github.com/cockroachdb/ui/blob/3a22d83c5ef1d20c6710b9b38cca92e52d52ae1c/packages/cluster-ui/src/sessions/sessionsPage.fixture.ts#L154)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

see comment above for cancelSession and cancelQuery funcs
</blockquote></details>

fixed
___
*[packages/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 175 at r3](https://reviewable.io/reviews/cockroachdb/ui/187#-MScKDp991mpZC7917mC:-MT655qV8lntlCTUIg33:b-7ql1td) ([raw file](https://github.com/cockroachdb/ui/blob/5dda8a4c8e93014cf67e01548245caeab64671e6/packages/cluster-ui/src/sessions/sessionsPage.fixture.ts#L175)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

see comment above for cancelSession and cancelQuery funcs
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2021-02-10 13:06 UTC, koorosh requested changes
> Reviewed 9 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: all files reviewed, 3 unresolved discussions (waiting on @dhartunian, @elkmaster, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/sessions/sessionsDetailsConnected.stories.tsx, line 22 at r2](https://reviewable.io/reviews/cockroachdb/ui/187#-MSWXXO18pyJaFzyA9cb:-MTAkMoGCBIKIerqgio9:bu6kykl) ([raw file](https://github.com/cockroachdb/ui/blob/5de4be2c931e6cd0ed94b4ba0cb47518bf6c0d38/packages/cluster-ui/src/sessions/sessionsDetailsConnected.stories.tsx#L22)):*
<details><summary><i>Previously, elkmaster wrote…</i></summary><blockquote>

no easy way to do it. we need to know id before the page renders. but we fetch sessions on didMount.
</blockquote></details>

ah, I see!
___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 142 at r4](https://reviewable.io/reviews/cockroachdb/ui/187#-MTB1iguEFnvRmUz8QfW:-MTB1iguEFnvRmUz8QfX:b-dpmq9p) ([raw file](https://github.com/cockroachdb/ui/blob/6ab01105b29f11893addd63e1e088ad082c11587/packages/cluster-ui/src/sessions/sessionsPage.tsx#L142)):*
> ```XML
> 
>   componentDidMount() {
>     this.props.refreshSessions();
> ```

Sessions page has to request nodes state as well. 
``` javascript
this.props.refreshNodes();
this.props.refreshNodesLiveness();
```

the same should be added to `componentDidUpdate` lifecycle hook


<!-- Sent from Reviewable.io -->

2021-02-10 13:36 UTC, koorosh approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187)* status: all files reviewed, 2 unresolved discussions (waiting on @dhartunian, @nathanstilwell, and @nkodali)

___
*[packages/cluster-ui/src/sessions/sessionsPage.tsx, line 142 at r4](https://reviewable.io/reviews/cockroachdb/ui/187#-MTB1iguEFnvRmUz8QfW:-MTB8wS06vR1KuLIdCuV:brihxkw) ([raw file](https://github.com/cockroachdb/ui/blob/6ab01105b29f11893addd63e1e088ad082c11587/packages/cluster-ui/src/sessions/sessionsPage.tsx#L142)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Sessions page has to request nodes state as well. 
``` javascript
this.props.refreshNodes();
this.props.refreshNodesLiveness();
```

the same should be added to `componentDidUpdate` lifecycle hook
</blockquote></details>

my fault, it's not required.


<!-- Sent from Reviewable.io -->

2021-02-10 18:52 UTC, dhartunian requested changes
Great! thanks for all the revisions on this.

The PR and commit message should contain a summary of what was added. What actions are we supporting, etc.
"All functions" is not sufficient here.

It should also contain an explanation of what's missing and *why* and future work will be necessary to figure the alerts out in the near future.

> Reviewed 4 of 10 files at r3, 9 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187#-:-MTCGg2i3MRXUZ94G-5d:bqj1y1r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nathanstilwell and @nkodali)



<!-- Sent from Reviewable.io -->

2021-02-16 15:51 UTC, dhartunian requested changes
@elkmaster please adjust the formatting of the commit message to wrap properly as defined here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187#-:-MTfXFtIBHm7o1OmCmAL:b-ptce1d)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @dhartunian, @koorosh, @nathanstilwell, and @nkodali)



<!-- Sent from Reviewable.io -->

2021-02-16 16:16 UTC, elkmaster commented
@dhartunian done

2021-02-16 17:32 UTC, dhartunian reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187#-:-MTftgs3B4YGoX81X8oW:bg7igkv)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @dhartunian, @koorosh, @nathanstilwell, and @nkodali)



<!-- Sent from Reviewable.io -->

2021-02-17 14:53 UTC, dhartunian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/ui/187#-:-MTkTsvf65wLCPLVUDY7:bg7igkv)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @dhartunian, @koorosh, @nathanstilwell, and @nkodali)



<!-- Sent from Reviewable.io -->

2021-02-18 09:15 UTC, merged